name: ObsidianDestroyer
main: com.pandemoneus.obsidianDestroyer.ObsidianDestroyer
version: 1.3.1
author: ['Pandemoneus', 'squidicuzz', 'alecgorge', 'Kaos']
depend: [Vault]

commands:
    obsidiandestroyer:
        description: ObisidanDestroyer
        usage: |
               /<command>
    od:
        description: ObisidanDestroyer
        usage: |
               /<command>